[management]
gitlab01 ansible_host=192.168.10.10 ansible_user=user1


[k8s_master]
master01 ansible_host=192.168.10.30 ansible_user=user1


[k8s_worker]
worker01 ansible_host=192.168.10.31 ansible_user=user1
worker02 ansible_host=192.168.10.32 ansible_user=user1


[database]
db01 ansible_host=192.168.10.40 ansible_user=user1
db02 ansible_host=192.168.10.41 ansible_user=user1


[harbor]
master01 ansible_host=192.168.10.30 ansible_user=user1
