---
- name: Server Init
  hosts:
  - management
  - harbor
  - k8s_master
  - k8s_worker
  - database
  become: yes
  roles:
    - docker


- name: Kubernetes Install
  hosts:
    - k8s_master
    - k8s_worker
  become: yes
  roles:
    - kubernetes


- name: Harbor Setup
  hosts: harbor
  become: yes
  roles:
    - harbor
